version: "3.1"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:10000
    volumes:
      - "./config:/var/lib/postgresql/config"
      - "./data:/var/lib/postgresql/data"
      - "./initdb:/docker-entrypoint-initdb.d"
    entrypoint:
      [
        "docker-entrypoint.sh",
        "-c",
        "config_file=/var/lib/postgresql/config/postgresql.conf",
      ]
